#!/usr/bin/env bash

set -euo pipefail

LEVEL="${LEVEL:-L1}"
BASE_MODEL_PATH="${BASE_MODEL_PATH:-Qwen/Qwen3-1.7B}"
BENCHMARK="${BENCHMARK:-AIME24}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
GPU_num="${GPU_num:-4}"
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-200}"

case "$LEVEL" in
    L0|l0)
        EXPERIMENT_NAME="${EXPERIMENT_NAME:-math_qwen3_1p7b_L0_4xA100}"
        TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-16}"
        TRAIN_SAMPLE_NUM="${TRAIN_SAMPLE_NUM:-4}"
        VALIDATE_SAMPLE_NUM="${VALIDATE_SAMPLE_NUM:-1}"
        MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-4096}"
        MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-4096}"
        VAL_FREQ="${VAL_FREQ:-10}"
        RESAMPLE_FREQ="${RESAMPLE_FREQ:-3}"
        export BASE_MODEL_PATH BENCHMARK CUDA_VISIBLE_DEVICES GPU_num TOTAL_TRAINING_STEPS
        export EXPERIMENT_NAME TRAIN_BATCH_SIZE TRAIN_SAMPLE_NUM VALIDATE_SAMPLE_NUM
        export MAX_PROMPT_LENGTH MAX_RESPONSE_LENGTH VAL_FREQ RESAMPLE_FREQ
        exec bash scripts/train/math/math_L0_single_agent.sh
        ;;
    L1|l1)
        EXPERIMENT_NAME="${EXPERIMENT_NAME:-math_qwen3_1p7b_L1_4xA100}"
        TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-16}"
        TRAIN_SAMPLE_NUM="${TRAIN_SAMPLE_NUM:-4}"
        VALIDATE_SAMPLE_NUM="${VALIDATE_SAMPLE_NUM:-5}"
        MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
        MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-4096}"
        VAL_FREQ="${VAL_FREQ:-10}"
        RESAMPLE_FREQ="${RESAMPLE_FREQ:-3}"
        export BASE_MODEL_PATH BENCHMARK CUDA_VISIBLE_DEVICES GPU_num TOTAL_TRAINING_STEPS
        export EXPERIMENT_NAME TRAIN_BATCH_SIZE TRAIN_SAMPLE_NUM VALIDATE_SAMPLE_NUM
        export MAX_PROMPT_LENGTH MAX_RESPONSE_LENGTH VAL_FREQ RESAMPLE_FREQ
        exec bash scripts/train/math/math_L1_prompt.sh
        ;;
    L2|l2)
        EXPERIMENT_NAME="${EXPERIMENT_NAME:-math_qwen3_1p7b_L2_4xA100}"
        TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-16}"
        TRAIN_SAMPLE_NUM="${TRAIN_SAMPLE_NUM:-4}"
        VALIDATE_SAMPLE_NUM="${VALIDATE_SAMPLE_NUM:-5}"
        MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-4096}"
        MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-4096}"
        VAL_FREQ="${VAL_FREQ:-10}"
        export BASE_MODEL_PATH BENCHMARK CUDA_VISIBLE_DEVICES GPU_num TOTAL_TRAINING_STEPS
        export EXPERIMENT_NAME TRAIN_BATCH_SIZE TRAIN_SAMPLE_NUM VALIDATE_SAMPLE_NUM
        export MAX_PROMPT_LENGTH MAX_RESPONSE_LENGTH VAL_FREQ
        exec bash scripts/train/math/math_L2_lora.sh
        ;;
    *)
        echo "Unsupported LEVEL: $LEVEL"
        echo "Use LEVEL=L0, LEVEL=L1, or LEVEL=L2"
        exit 1
        ;;
esac
