#!/usr/bin/env bash

set -euo pipefail

BASE_MODEL_PATH="${BASE_MODEL_PATH:-Qwen/Qwen3-1.7B}"
BENCHMARK="${BENCHMARK:-AIME24}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
TOTAL_GPU_num="${TOTAL_GPU_num:-4}"
GPU_num="${GPU_num:-2}"
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-200}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-math_qwen3_1p7b_L3_4xA100}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-16}"
TRAIN_SAMPLE_NUM="${TRAIN_SAMPLE_NUM:-4}"
VALIDATE_SAMPLE_NUM="${VALIDATE_SAMPLE_NUM:-1}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-4096}"
VAL_FREQ="${VAL_FREQ:-10}"
RESAMPLE_FREQ="${RESAMPLE_FREQ:-3}"
MODEL_CHECKPOINTS_DIR="${MODEL_CHECKPOINTS_DIR:-checkpoints}"
PPO_DEFAULT_LOCAL_DIR="${PPO_DEFAULT_LOCAL_DIR:-$MODEL_CHECKPOINTS_DIR}"
CHECKPOINT_DIR="${CHECKPOINT_DIR:-$MODEL_CHECKPOINTS_DIR}"

export BASE_MODEL_PATH BENCHMARK CUDA_VISIBLE_DEVICES TOTAL_GPU_num GPU_num
export TOTAL_TRAINING_STEPS EXPERIMENT_NAME TRAIN_BATCH_SIZE TRAIN_SAMPLE_NUM
export VALIDATE_SAMPLE_NUM MAX_PROMPT_LENGTH MAX_RESPONSE_LENGTH
export VAL_FREQ RESAMPLE_FREQ MODEL_CHECKPOINTS_DIR PPO_DEFAULT_LOCAL_DIR CHECKPOINT_DIR

exec bash scripts/train/math/math_L3_model.sh
